### ISSUE TITLE
Going back to schedule

### ISSUE THREAD

**Issue by snakedog116** [yracine/device-type.myecobee#10]
The app currently seems to put the thermostat into 'hold'. Which then won't allow for it to go back to schedule at the next scheduled change.

We found this out when in the AM the system didn't pre-heat (Smart Recovery Heat) our house and it was still 17 celcius when we woke up this morning.

Is there a way to make this smartapp only adjust the home/away/sleep settings until the next schedule? or for the next 'X' hrs, or something like that? Ideally it wouldn't actually put a 'hold' on the system and would instead act the same way as the ecobee does when it detects, or doesn't detect motion. (Smart Home/Smart Away instead of 'Away and Hold'.)

I'm not sure if the Ecobee API allows you to access any of those settings. But thought I'd ask.

**Comment by yracine** [comment]
Hello,

Please refer to configuration section of the ST community wiki (section 3b).

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device

Please support the developer!
