### ISSUE TITLE
Frequent "too many exceptions/errors" messages

### ISSUE THREAD

**Issue by jkeenest** [yracine/device-type.myecobee#12]
Need to re-authenticate frequently.  The message "ecobee3RemoteSensorInit>too many exceptions/errors or unauthorized exception, doRequest>exception groovy.net.http.HttpResponseException: Internal Server Error for null (10 errors), need to re-authenticate at ecobee..."  This happens almost daily after authenticating and then repeatedly when polling.
![img_4323](https://cloud.githubusercontent.com/assets/10226529/11118907/934c0290-8913-11e5-942e-826eba96039d.jpg)

**Comment by kruznby** [comment]
Did you do step 7 by changing the input value?  I just started using this this weekend and forgot to do that step.  I did it, and for the last 4 days I have had no issues.  It could be only a coincidence though as I have not been using it long.

7) Update device's preferences (optional, input parameters)

/*********************************************************************************************

Go to https://graph.api.smartthings.com/device/list

Click on the My ecobee device that you just created

Click on Preferences (edit)

You only need to edit the following parameters

(a) <trace> when needed, set to true to get more tracing (no spaces)
(b) <holdType> set to nextTransition or indefinite (by default, no spaces) 
see http://www.ecobee.com/home/developer/api/documentation/v1/functions/SetHold.shtml 
for more details 
/************************************************************************

**Comment by jkeenest** [comment]
Those options appear irrelevant to authentication. @yracine is anyone else getting these errors repeatedly?

**Comment by snakedog116** [comment]
I'm having these issues as well. For me it has been an authentication issue. If I re-open the smartapp it shows that it isn't logged in.

I've had to log in about 4 times in the past 2 weeks.

**Comment by yracine** [comment]
Hi there,

FYI, if you have any question or issue about My Ecobee Device and related smartapps, 
a new ST community wiki has been created  for that purpose.

Please consult the following link about My Ecobee Device:

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device

There is a 'known issues' and 'troubleshooting' sections under My ecobee Device and some more complex smartapps that can help you solve  most of your issues.

P.S. Please refer to item 6 under My Ecobee Device' troubleshooting section for any connection issue between ST and ecobee. My code does not have any control on the state of this connection.  However, it will notify you if there is any issue.

Regards.

**Comment by yracine** [comment]
Hi,

According to some feedback from several users, my code is now working with the
workaround that I implemented about the connection issues.

My Ecobee Device, MyEcobeeInit, Ecobee3RemoteSensorInit need to be resync first at the main branch (just save & publish the code in the IDE).

https://github.com/yracine/device-type.myecobee

Regards.

P.S. My code now ignores some exceptions that are thrown by the ST cloud backend (i.e. groovyx.net.http.HttpResponseException ) for some users.

Please support the developer  :grinning:

**Comment by maferguson** [comment]
I had so many exceptions that I ended up removing the SmartApps.

**Comment by yracine** [comment]
Hi, I'm afraid that there is nothing I can do on my end.

I reported the issue to ST, and they said that they are working on improving their
ST cloud backend.  See below:

Continuing the discussion from [Initial Setup for Ecobee3, Smart-SI, EMS, Smart-02 thermostats - My custom Ecobee Device](https://community.smartthings.com/t/initial-setup-for-ecobee3-smart-si-ems-smart-02-thermostats-my-custom-ecobee-device/17260/170):

[quote="yvesracine, post:170, topic:17260, full:true"]
Hi @slagle, 

Now, I'm starting to believe that ST cloud backend is throwing some exceptions
for some users (like groovyx.net.http.HttpResponseException ) when it should not.

This affects MyEcobee device as my code is doing some exception handling in order
to avoid losing the access token (when I should probably not do anything in this case,
and just trap it).

After checking in other forum threads, I found out that ST is also throwing groovyx.net.http.ResponseParseException for no reason as per this thread (see the bottom of it):

https://community.smartthings.com/t/grovestreams-smartthings-quickstart/9189

My questions to ST  (not to you specifically) are:

(1) Is it possible that some exceptions in DevConn are thrown for no reason?

(2) If yes, are there any platform updates planned to correct the situation?


Regards.
[/quote]

Continuing the discussion from [Initial Setup for Ecobee3, Smart-SI, EMS, Smart-02 thermostats - My custom Ecobee Device](https://community.smartthings.com/t/initial-setup-for-ecobee3-smart-si-ems-smart-02-thermostats-my-custom-ecobee-device/17260/115):

[quote="slagle, post:115, topic:17260, full:true"]
We are working on improving our end of Cloud and Lan connected devices. We can only control what we can control. 

Aside from that, the only recommendation I can recommend is to reduce polling intervals. This will rule out your connection being limited by the external API. I know MyQ and Ecobee are very specific about their polling intervals. I have read on their forums they recommend not polling more than every 30 seconds (maybe 10 seconds? I found both numbers but 30 second intervals show up more). 

I'd find it unlikely that you are hitting this limit, but I have also read on their forums something along the lines of "Our servers ensure that your thermostat is protected from attacks against it." I wonder if you are hitting that "wall" so to speak.

I say all this not to say it isn't on our end at all, but it may not be all on our end. Try reducing polling intervals and see if that resolves these timeout connection issues. :smile: I'd be interested to know. Maybe start by doubling your currently polling intervals.

Most of the other threads @yvesracine mentioned (with the exception of MyQ) are not related to this and are either related to a platform outage or DHCP issues. (We have a fix for wemo coming out in a little while that allows us to see and change the IP when the wemo Ip changes locally)
[/quote

**Comment by yracine** [comment]
Hi,


Good news: after a lot of investigation and some hard work, I found a permanent workaround to the connection issues between ST and ecobee.  

However, please take note of the following:

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Notes_to_MyEcobee_Device_Users_-_Contribution_is_now_required

Regards.

P.S. If you want to take advantage of the new version (faster response times & no more exceptions), please send me a donation and you'll be part of the upgrade list.

:grinning:

**Comment by maferguson** [comment]
I briefly saw an email about accessing the update but it is gone.
