### ISSUE TITLE
Ecobee API Update: expires_in should be seconds, not minutes

### ISSUE THREAD

**Issue by SANdood** [yracine/device-type.myecobee#13]
Today ecobee updated their API and their documentation. Of particular note is that the token expires_in time that is returned by the API is now documented as seconds, not minutes. Thus, you will need to update both MyEcobeeInit and MyEcobeeDevice to NOT multiply the returned value by 60 when calculating the expiry time.

Documentation says the token has to be refreshed once every hour, and it should not require a re-login more frequently than once per year...

I'm not sure if this has always been seconds (you know better than I), but if so, it could be the root cause of the token auth timeout issues...

**Comment by yracine** [comment]
Thnx, it's an issue, but it's not the only one... There is some form of rate limiting now either on the ST or the ecobee side..Sounds like the perfect storm!

**Comment by SANdood** [comment]
Hmm…I don’t seem to be experiencing any rate limiting since I’ve implemented the change…once the tokens successfully refreshed, it’s been humming along without any sort of timeout error (save for one execution timeout for running more than 20 seconds…I’m pretty sure that’s a latent ST bug).

 

Perhaps this is due to the “fork” I made to your code – my version now polls frequently for updates (every 5-15 seconds), but it always first checks if anything has changed in the desired data points; I suspect that my code avoids the throttles because it ONLY calls the heavyweight GET calls when it knows something has changed (and things do get reported as changed by the ecobee API *MUCH* more frequently than the documented 3-5 minutes)..

 

(Likewise, my version of ecobeeRemoteSensorsInit differs from yours in that it waits for MyEcobeeDevice to find and report (sendEvent) a change to the remote sensors; this instead of polling for changes again reduces the heavyweight ecobee API calls to a minimum, while reporting RemoteSensor change events within a few seconds of their occurrence.)

 

But, hey – we’ve agreed to go separate ways…just offering my perspective – feel free to ignore it…

 

Thanks!

                Barry
