### ISSUE TITLE
Having issues once installed.

### ISSUE THREAD

**Issue by matthewjhunt** [yracine/device-type.myecobee#17]
I was able to get everything installed and my iphone shows the new ecobee device. I opened it and hit refresh and it did update to what my thermostat was currently doing. The problem was when I tried to use any of the buttons in the new smart things device. When I hit the "heat" button it turns to "off" and my thermostat did turn off. If I hit it again when it says off, the button then says "heat" but on my thermostat it actually puts the system into cool mode.

Most the other buttons don't do anything when pressed. I would assume the little home button should give you an option to set it to "away" but it doesn't.

Also the arrows that seem like they should adjust the temperature up or down, do nothing when pressed.

I did just buy my ecobee3 and smart things hub so I'm not sure if that is part of the problem.

**Comment by yracine** [comment]
Please uninstall and re-install the device as I cannot reproduce your issue.
