### ISSUE TITLE
if you're going to charge, you need to respond to people who pay you

### ISSUE THREAD

**Issue by honestbleeps** [yracine/device-type.myecobee#18]
I'm 100% in support of you wanting to be compensated for your work, and you deserve every penny.

I am not in support of you charging for your work, but then not providing people the code they paid for, nor responding when they write to inquire about it.

It has been 5 days since I paid, and 3 days since I wrote you asking how I get the code I paid for, and no response.

I don't like resorting to posting an issue on your github page, but I'm left with no other choice at this point. This is not an acceptable way to run a project where you ask for peoples' money.

Please provide the community an update on how you will handle payments go forward.

**Comment by yracine** [comment]
Hi,
You must have missed the update I posted in the ST community forum.

https://community.smartthings.com/t/my-new-ecobee-device-exceptions-issues-to-be-resolved/31922/15

Regards.

You will receive the code  by email as a tempory link to a google drive folder.
à

**Comment by honestbleeps** [comment]
actually, I saw that update, and was waiting for my email to the google drive folder. It has been 5 days... what's the expected wait time for the email?  That should be made clear to users who pay for your product (it's now a product, since you're charging for it)

**Comment by honestbleeps** [comment]
sorry, I didn't mean to come off as confrontational - so I will make a constructive suggestion:

it's best to expect that people may not read every single post in a 39 page long thread, especially if the place they look for info is your github, etc. So at the spot where you ask for payment (the paypal donate button) - it would be optimal to add some text that explains the process and/or wait time in that spot.
