### ISSUE TITLE
MonitorAndSetEcobeeHumidity gets 'unexpected error' when clicking 'Done'.

### ISSUE THREAD

**Issue by lymanepp** [yracine/device-type.myecobee#23]
The only parameters specified are thermostat and humidity sources.

**Comment by yracine** [comment]
Sorry, but I cannot reproduce your issue. Make sure to specify a valid outdoor humidity sensor with the Relative Humidity Measurement capabilty.

IF you have any other issues, please send an email with your logs at services@maisonsecomatiq.com.

For live logging, go to 

https://graph.api.smartthings.com/ide/logs

- And click on the smartapp at the top of the screen to filter only the events coming from the smartapp.
- Set detailed notification to true in the smartapp.

Regards.

**Comment by lymanepp** [comment]
I am using AccuWeather Connect as my outdoor "sensor". It appears to provide humidity.
https://support.smartthings.com/hc/en-us/articles/208319643-AccuWeather

**Comment by lymanepp** [comment]
Here's the error from live logging (and I learned something new).

3:30:05 PM: error java.lang.NullPointerException: Cannot invoke method hasCapability() on null object @ line 500

**Comment by yracine** [comment]
As I wrote earlier, send me the detailed logs to services@maisonsecomatiq.com.  Otherwise, I cannot get the full trace of your error.

Regards.
