### ISSUE TITLE
Method to Update

### ISSUE THREAD

**Issue by john022662** [yracine/device-type.myecobee#25]
Hi yracine,

I have purchased and installed "My Ecobee Bundle for SmartThings" and also paid and extra $25 for support. Hoping you can help me with a couple questions.

Is there any indication of the Furnace Fan Running other that from modes: (Fan Only, or Heat, or Cool)? I use your smartapps as part of WebCoRE to start ceiling fans and it appears that when the furnace fan continues to run after a heat mode event, there is no indication that the furnace fan is still running and my ceiling fans stop?

Also, is there an easy way to get updates from you on the Smartapps and Device Handlers that  I use (DH's = "My Ecobee Device", My Ecobee Switch"; SA = "ecobeeStatetriggerHA", MyEcobeeInit).  Possibly by use of GitHub? Could you provide some information for this?

**Comment by yracine** [comment]
Hi,

Sorry, I don't provide updates via github as this is copyright code.  You need to use the sellfy link and copy and paste the code into the IDE.  SmartThings was supposed to create a marksetspace for developers like me, but they have never done it.

The only exception is the complimentary smartapps like _ecobeeStateTriggerHA._

https://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Github_integration_for_the_complimentary_apps

About the fan issue, I'm sorry but that's the only way to get the fan state.... I get it from the equipmentStatus attribute directly from the ecobee APIs.

Regards.

**Comment by john022662** [comment]
Thanks Racine…

 

This works for me. I appreciate the feedback.
