### ISSUE TITLE
Update ecobeeChangeMode

### ISSUE THREAD

**Issue by n3pjk** [yracine/device-type.myecobee#27]
I have updated ecobeeChangeMode to support multiple contact sensors, so it can go into an open, or "off", mode when doors are left open for a period of time. Also added multiple switch support, more notification options, notification restrictions to limit when to send notifications, and support for Echo Speaks devices.  The UI is streamlined some, hiding extraneous options when not needed.

I will be making a PR against this issue shortly.

**Comment by yracine** [comment]
Hi, as I wrote to you over email, there is already a smartapp called _WindowAndDoorOpen_ for open contacts.  So, I'm not planning to merge the code as the use cases are different. I prefer to have 2 different smartapps for the use cases.
