### ISSUE TITLE
I am unable to delete both MyEcobeeInit and EcobeeRemoteSensorInit apps from SmartThings

### ISSUE THREAD

**Issue by ydogandjiev** [yracine/device-type.myecobee#29]
I am trying to remove the MyEcobeeInit and EcobeeRemoteSensorInit apps from SmartThings so that I can test out the built-in integration and compare it since I've seen some issues with the custom device handlers (e.g. 0% battery on all my remote sensors). Unfortunately, no matter how many times I select these app in SmartThings and use the Delete option nothing happens. The apps cannot be removed. Please fix this.

I tried deleting the apps both from here:
![image](https://user-images.githubusercontent.com/3357245/98497841-20288880-21fa-11eb-975e-4a161f9e81b7.png)

And from here:
![image](https://user-images.githubusercontent.com/3357245/98497844-23237900-21fa-11eb-9b84-2e48d56f19b2.png)

But neither option worked.

**Comment by ydogandjiev** [comment]
I can't delete the app via the IDE either:
![image](https://user-images.githubusercontent.com/3357245/98498446-a1cce600-21fb-11eb-806d-b6ec2c423746.png)

Looks like I am stuck.

**Comment by ydogandjiev** [comment]
I can't delete any of the devices created by these apps either:
![image](https://user-images.githubusercontent.com/3357245/98498545-e48ebe00-21fb-11eb-9c47-c2c16b599bb9.png)

**Comment by yracine** [comment]
Hi, please refer to the ST community wiki for troubleshooting. You need to delete any reference to the devices (in smartapps, automations or webCore scripts).

See  https://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Issue_.2313:_I.27d_like_to_uninstall_My_ecobee_device_and_its_remote_sensors

**Comment by ydogandjiev** [comment]
Thank @yracine; that did the trick! I was able to delete all the devices and smart apps after which I re-added them and everything started working great again. Also, your latest DH update resolved the battery issue I was seeing with the sensors. Thanks!
